### ISSUE TITLE
Лучше сделай export default new MovieDBServices(); в файле, в котором сервис определяется

### ISSUE THREAD

**Issue by didolf** [Slade3312/Movies-App#5]
https://github.com/Slade3312/Movies-App/blob/4ae674cc94b328b9a8521d47e47112e36374635f/src/components/App/App.jsx#L10

Зачем хранить несколько экземпляров, если можно один.

А еще лучше сделай статическими свойствами класса(правда возможно придется babel подкрутить - если так, тогда не парься).

**Comment by Slade3312** [comment]
fix: create static metod class
