### ISSUE TITLE
Поменяй на забинденную функцию

### ISSUE THREAD

**Issue by didolf** [Slade3312/Movies-App#6]
https://github.com/Slade3312/Movies-App/blob/4ae674cc94b328b9a8521d47e47112e36374635f/src/components/App/App.jsx#L60
```js
    <Header moviesSearchQuery={this.moviesSearchQuery.bind(this)} />
```
А еще лучше - забинди в конструкторе(`this.moviesSearchQuery = this.moviesSearchQuery.bond(this);`)

**Comment by didolf** [comment]
https://github.com/Slade3312/Movies-App/blob/4ae674cc94b328b9a8521d47e47112e36374635f/src/components/Header/Header.jsx#L38 - и тут
Почитай про биндинг в конструкторе и зачем это нужно

**Comment by Slade3312** [comment]
commit fix: binding function
