### ISSUE TITLE
Сделай словарь как enum, а то непонятно, че за двойка

### ISSUE THREAD

**Issue by didolf** [Slade3312/Movies-App#8]
https://github.com/Slade3312/Movies-App/blob/4ae674cc94b328b9a8521d47e47112e36374635f/src/components/MoviesList/MoviesList.jsx#L43

**Comment by didolf** [comment]
Ну и вообще плохо, что компонент знает про эти табы, лучше как-то выше это решить.

**Comment by didolf** [comment]
У него же задача - зафетчить и вынести. Может тогда и фетчить выше, пусть только отрисовывает

**Comment by Slade3312** [comment]
fix: fix  magic number in activeTab

**Comment by Slade3312** [comment]
Магические числа я убрал, вынести состояние таба не знаю как, ведь я не обновляю компонент пока он в состоянии hidden , и при переключении таба именно (activeTab === 'active_rated' && prevProps.activeTab !== 'active_rated') этим я узнаю что компонент виден и нужно его обновить(так или иначе что- то прийдется передать в компонент почему бы не таб )

**Comment by Slade3312** [comment]
Можно через hoc убрать всю логику но у меня состояние таб еще ниже прокидывается к карточке фильма
